baseURL = "https://mattcdrake.com"
languageCode = "en-us"
theme = "cocoa"
contentdir = "content"
publishdir = "public"
author = "Matt Drake"
title = "Matt Drake"

[permalinks]
blog = "blog/:slug/"

[[menu.main]]
name = "Blog"
weight = -120
identifier = "blog"
url = "/blog/"

[[menu.main]]
name = "About"
weight = -110
identifier = "about"
url = "/fixed/about"

[[menu.main]]
name = "Projects"
weight = -100
identifier = "projects"
url = "/projects/"

[[menu.main]]
name = "Reading List"
weight = -90
identifier = "reading"
url = "/fixed/reading"

[params]
latestpostscount = 20
author = "Matt Drake"
dateform = "2 Jan 2006"
github = "//github.com/mattcdrake"
twitter = "//twitter.com/matt_c_drake"

avatar = "img/avatar.jpg"
