baseURL = "https://mattcdrake.com"
languageCode = "en-us"
theme = "cocoa"
contentdir = "content"
publishdir = "public"
author = "Matt Drake"
title = "Matt Drake"

[permalinks]
blog = "blog/:slug/"

[[menu.main]]
name = "Blog"
weight = -120
identifier = "blog"
url = "/blog/"

[[menu.main]]
name = "About"
weight = -110
identifier = "about"
url = "/fixed/about"

[[menu.main]]
name = "Games"
weight = -100
identifier = "games"
url = "/games/"

[[menu.main]]
name = "Bookshelf"
weight = -90
identifier = "bookshelf"
url = "/fixed/bookshelf"

[[menu.main]]
name = "Twitter"
weight = -80
url = "https://twitter.com/matt_c_drake"

[params]
latestpostscount = 20
author = "Matt Drake"
dateform = "2 Jan 2006"

avatar = "img/avatar.jpg"
noshowreadtime = true